# Generated by Django 4.1.4 on 2023-01-04 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_sold_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sold_car',
        ),
    ]
