# Generated by Django 4.1.4 on 2023-01-05 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_delete_sold_car'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car_list',
            new_name='CarList',
        ),
        migrations.AlterModelManagers(
            name='carlist',
            managers=[
            ],
        ),
    ]
