# Generated by Django 4.1.4 on 2023-01-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_rename_car_list_carlist_alter_carlist_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='upload',
            field=models.ImageField(default='', upload_to='uploads'),
        ),
    ]
