# Generated by Django 4.1.4 on 2023-01-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_alter_carlist_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlist',
            name='upload',
            field=models.ImageField(default='', upload_to='templates/static'),
        ),
    ]
