# Generated by Django 4.1.4 on 2023-01-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_alter_carlist_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlist',
            name='seller_mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
